cleanup

diff --git a/.github/workflows/bump_build_uv.yml b/.github/workflows/bump_build_uv.yml
--- a/.github/workflows/bump_build_uv.yml
+++ b/.github/workflows/bump_build_uv.yml
@@ -38,13 +38,16 @@ jobs:
         env:
             NEW_VERSION: ${{ steps.latest.outputs.uv-version }}
         run: |
-          sed "s/^\(ARG UV_VERSION=\).*/\1${NEW_VERSION}/" ${DOCKERFILE_PATH}
           sed -i "s/^\(ARG UV_VERSION=\).*/\1${NEW_VERSION}/" ${DOCKERFILE_PATH}
           RETURN_CODE=$?
-          echo $RETURN_CODE
-          echo "updated=true" >> ${GITHUB_OUTPUT}
-          echo $(git status)
-          git diff | cat
+          if [ ${RETURN_CODE} -eq 0 ]; then
+            echo "Successfully update uv version"
+            echo "updated=true" >> ${GITHUB_OUTPUT}
+          else
+            echo "Failed to update uv version"
+            echo "updated=false" >> ${GITHUB_OUTPUT}
+            exit 1
+          fi
 
       - name: Create Pull Request
         id: create-pr-ok
